# Installing Numpy
---
* Linear Algebra for Python
* With Acaconda install using command prompt:  "__conda install numpy__" 
* Without Acaconda install using command prompt or terminal: "__pip install numpy__"

# NumPy Arrays
---

In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
#  cast an list into a numpy array
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [9]:
#  Matrix
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
#  cast a list of lists into a numpy matrix 
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#  numpy range function (left inclusive)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#  can also add step size as the 3rd input
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
#  Arrays of zeros
np.zeros(3)

array([ 0.,  0.,  0.])

In [15]:
#  Matrix of zeros
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [18]:
#  Matrix of ones
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [20]:
#  Start at 0 and end at 5 and create 10 evenly spaced values
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [21]:
#  Identity matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random numbers
---

In [22]:
#  random numbers (0,1) 
np.random.rand(5)

array([ 0.25072378,  0.16324894,  0.04773104,  0.13037294,  0.60784707])

In [24]:
#  random matrix
np.random.rand(5,5)

array([[ 0.29034976,  0.58391077,  0.37285023,  0.88077942,  0.66207877],
       [ 0.35144189,  0.88922288,  0.750277  ,  0.82083063,  0.4546168 ],
       [ 0.30832419,  0.59690328,  0.51996655,  0.6769487 ,  0.90920207],
       [ 0.96053629,  0.53084798,  0.44747975,  0.33263272,  0.12562452],
       [ 0.22620234,  0.58895364,  0.21430385,  0.57836463,  0.63937759]])

In [25]:
#  normal distribution centered around 0
np.random.randn(2)

array([-0.11329208, -2.48152442])

In [27]:
#  10 random integers between 1 and 100 (including 1 and not 100). 
np.random.randint(1,100,10)

array([54,  1, 37, 21, 58, 11, 84, 24, 43, 49])

##  Array Attributes
---

In [42]:
#  array range 
arr = np.arange(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
#  random integers between 0 and 50, 10 of them
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([ 9, 41, 20, 40, 41, 33, 22, 16,  3, 35])

In [32]:
#  reshape 25 element arr list into a 5x5 matrix
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
#  maximum array value
ranarr.max()

41

In [35]:
#  minimum array value
ranarr.min()

3

In [36]:
#  index position of max value
ranarr.argmax()

1

In [37]:
#  index value of min value
ranarr.argmin()

8

In [45]:
#  array dimension
arr.shape

(25,)

In [46]:
#  data type of array
arr.dtype

dtype('int32')

## Array Indexing and Selection
---

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#  numpy indexing is just like a list operation
arr[4]

4

In [12]:
#  slicing works the same way, here is everything fourth and beyond 
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [9]:
#  last element
arr[-1]

10

In [10]:
#  second to last element
arr[-2]

9

In [11]:
#  everything except first and last
arr[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#  grab the zero through (but not including) 6th array elements
slice_of_arr = arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
#  change the slice values to all be 99
slice_of_arr[:]=99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
#  But be careful because that changed the arr!!!
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
#  creating an array copy that doesn't get overwritten
arr_copy = arr.copy()

In [20]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
#  overwrite the array copy
arr_copy[:]=100

In [23]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
#  original array unchanged, only the copy is changed.  
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Matrix Indexing and Selection
---

In [1]:
import numpy as np

In [2]:
#  2D matrix
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [3]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
#  double brack format [row][column], indexing starts at ZERO.  
arr_2d[0][0]

5

In [5]:
#  first row
arr_2d[0]

array([ 5, 10, 15])

In [6]:
arr_2d[1][1]

25

In [7]:
#  Single bracket notation [row,column]
arr_2d[1,2]

30

In [10]:
#  matrix slice notation
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [11]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

## Conditional Selection
---

In [12]:
arr = np.arange(1,11)

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#  Boolean Array, True for values greater than 5
bool_arr = arr > 5

In [16]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [17]:
#  Pass the boolean array into the index argument to select only True entries
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [18]:
#  This is more common notation
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [20]:
arr[arr<3]

array([1, 2])

In [21]:
arr_2d = np.arange(50).reshape(5,10)

In [22]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [24]:
#  Grab [[13,14],[23,24]] matrix
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Numpy Operations
---
* Array with Array
* Array with Scalars
* Universal Array Functions

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#  array addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
#  array subtraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
#  element-wise multiplication
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
#  Scalar addition
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [10]:
#  Scalar multiplication
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [11]:
#  note 0/0 yields nan during numpy array division
arr / arr

C:\Users\Nicholas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [12]:
#  still an error, but you get 1/0 = inf
1/arr

C:\Users\Nicholas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [13]:
#  elements wise power
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [14]:
#  Element wise square root
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [15]:
#  element wise exponentional
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [16]:
#  max value
np.max(arr)

10

In [17]:
#  sin/cos
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [18]:
#  element-wise logarithm of array values
np.log(arr)

C:\Users\Nicholas\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])